USE elecciones;
INSERT INTO departamento (id_departamento, nombre) VALUES (1, 'Guatemala');
INSERT INTO departamento (id_departamento, nombre) VALUES (2, 'El Progreso');
INSERT INTO departamento (id_departamento, nombre) VALUES (3, 'Sacatepéquez');
INSERT INTO departamento (id_departamento, nombre) VALUES (4, 'Chimaltenango');
INSERT INTO departamento (id_departamento, nombre) VALUES (5, 'Escuintla');
INSERT INTO departamento (id_departamento, nombre) VALUES (6, 'Santa Rosa');
INSERT INTO departamento (id_departamento, nombre) VALUES (7, 'Sololá');
INSERT INTO departamento (id_departamento, nombre) VALUES (8, 'Totonicapán');
INSERT INTO departamento (id_departamento, nombre) VALUES (9, 'Quetzaltenango');
INSERT INTO departamento (id_departamento, nombre) VALUES (10, 'Suchitepéquez');
INSERT INTO departamento (id_departamento, nombre) VALUES (11, 'Retalhuleu');
INSERT INTO departamento (id_departamento, nombre) VALUES (12, 'San Marcos');
INSERT INTO departamento (id_departamento, nombre) VALUES (13, 'Huehuetenango');
INSERT INTO departamento (id_departamento, nombre) VALUES (14, 'Quiché');
INSERT INTO departamento (id_departamento, nombre) VALUES (15, 'Baja Verapaz');
INSERT INTO departamento (id_departamento, nombre) VALUES (16, 'Alta Verapaz');
INSERT INTO departamento (id_departamento, nombre) VALUES (17, 'Petén');
INSERT INTO departamento (id_departamento, nombre) VALUES (18, 'Izabal');
INSERT INTO departamento (id_departamento, nombre) VALUES (19, 'Zacapa');
INSERT INTO departamento (id_departamento, nombre) VALUES (20, 'Chiquimula');
INSERT INTO departamento (id_departamento, nombre) VALUES (21, 'Jalapa');
INSERT INTO departamento (id_departamento, nombre) VALUES (22, 'Jutiapa');