USE elecciones;
INSERT INTO municipio (id_municipio, nombre, id_departamento) VALUES (0101, 'Guatemala', 01);
INSERT INTO municipio (id_municipio, nombre, id_departamento) VALUES (0102, 'Santa Catarina Pinula', 01);
INSERT INTO municipio (id_municipio, nombre, id_departamento) VALUES (0103, 'San José Pinula', 01);
INSERT INTO municipio (id_municipio, nombre, id_departamento) VALUES (0104, 'San José del Golfo', 01);
INSERT INTO municipio (id_municipio, nombre, id_departamento) VALUES (0105, 'Palencia', 01);
INSERT INTO municipio (id_municipio, nombre, id_departamento) VALUES (0106, 'Chinautla', 01);
INSERT INTO municipio (id_municipio, nombre, id_departamento) VALUES (0107, 'San Pedro Ayampuc', 01);
INSERT INTO municipio (id_municipio, nombre, id_departamento) VALUES (0108, 'Mixco', 01);
INSERT INTO municipio (id_municipio, nombre, id_departamento) VALUES (0109, 'San Pedro Sacatepéquez', 01);
INSERT INTO municipio (id_municipio, nombre, id_departamento) VALUES (0110, 'San Juan Sacatepéquez', 01);
INSERT INTO municipio (id_municipio, nombre, id_departamento) VALUES (0111, 'San Raymundo', 01);
INSERT INTO municipio (id_municipio, nombre, id_departamento) VALUES (0112, 'Chuarrancho', 01);
INSERT INTO municipio (id_municipio, nombre, id_departamento) VALUES (0113, 'Fraijanes', 01);
INSERT INTO municipio (id_municipio, nombre, id_departamento) VALUES (0114, 'Amatitlán', 01);
INSERT INTO municipio (id_municipio, nombre, id_departamento) VALUES (0115, 'Villa Nueva', 01);
INSERT INTO municipio (id_municipio, nombre, id_departamento) VALUES (0116, 'Villa Canales', 01);
INSERT INTO municipio (id_municipio, nombre, id_departamento) VALUES (0117, 'Petapa', 01);
INSERT INTO municipio (id_municipio, nombre, id_departamento) VALUES (0201, 'Guastatoya', 02);
INSERT INTO municipio (id_municipio, nombre, id_departamento) VALUES (0202, 'Morazán', 02);
INSERT INTO municipio (id_municipio, nombre, id_departamento) VALUES (0203, 'San Agustín Acasaguastlán', 02);
INSERT INTO municipio (id_municipio, nombre, id_departamento) VALUES (0204, 'San Cristóbal Acasaguastlán', 02);
INSERT INTO municipio (id_municipio, nombre, id_departamento) VALUES (0205, 'El Jícaro', 02);
INSERT INTO municipio (id_municipio, nombre, id_departamento) VALUES (0206, 'Sansare', 02);
INSERT INTO municipio (id_municipio, nombre, id_departamento) VALUES (0207, 'Sanarate', 02);
INSERT INTO municipio (id_municipio, nombre, id_departamento) VALUES (0208, 'San Antonio la Paz', 02);
INSERT INTO municipio (id_municipio, nombre, id_departamento) VALUES (0301, 'Antigua Guatemala', 03);
INSERT INTO municipio (id_municipio, nombre, id_departamento) VALUES (0302, 'Jocotenango', 03);
INSERT INTO municipio (id_municipio, nombre, id_departamento) VALUES (0303, 'Pastores', 03);
INSERT INTO municipio (id_municipio, nombre, id_departamento) VALUES (0304, 'Sumpango', 03);
INSERT INTO municipio (id_municipio, nombre, id_departamento) VALUES (0305, 'Santo Domingo Xenacoj', 03);
INSERT INTO municipio (id_municipio, nombre, id_departamento) VALUES (0306, 'Santiago Sacatepéquez', 03);
INSERT INTO municipio (id_municipio, nombre, id_departamento) VALUES (0307, 'San Bartolomé Milpas Altas', 03);
INSERT INTO municipio (id_municipio, nombre, id_departamento) VALUES (0308, 'San Lucas Sacatepéquez', 03);
INSERT INTO municipio (id_municipio, nombre, id_departamento) VALUES (0309, 'Santa Lucía Milpas Altas', 03);
INSERT INTO municipio (id_municipio, nombre, id_departamento) VALUES (0310, 'Magdalena Milpas Altas', 03);
INSERT INTO municipio (id_municipio, nombre, id_departamento) VALUES (0311, 'Santa María de Jesús', 03);
INSERT INTO municipio (id_municipio, nombre, id_departamento) VALUES (0312, 'Ciudad Vieja', 03);
INSERT INTO municipio (id_municipio, nombre, id_departamento) VALUES (0313, 'San Miguel Dueñas', 03);
INSERT INTO municipio (id_municipio, nombre, id_departamento) VALUES (0314, 'Alotenango', 03);
INSERT INTO municipio (id_municipio, nombre, id_departamento) VALUES (0315, 'San Antonio Aguas Calientes', 03);
INSERT INTO municipio (id_municipio, nombre, id_departamento) VALUES (0316, 'Santa Catarina Barahona', 03);
INSERT INTO municipio (id_municipio, nombre, id_departamento) VALUES (0401, 'Chimaltenango', 04);
INSERT INTO municipio (id_municipio, nombre, id_departamento) VALUES (0402, 'San José Poaquil', 04);
INSERT INTO municipio (id_municipio, nombre, id_departamento) VALUES (0403, 'San Martín Jilotepeque', 04);
INSERT INTO municipio (id_municipio, nombre, id_departamento) VALUES (0404, 'Comalapa', 04);
INSERT INTO municipio (id_municipio, nombre, id_departamento) VALUES (0405, 'Santa Apolonia', 04);
INSERT INTO municipio (id_municipio, nombre, id_departamento) VALUES (0406, 'Tecpán Guatemala', 04);
INSERT INTO municipio (id_municipio, nombre, id_departamento) VALUES (0407, 'Patzún', 04);
INSERT INTO municipio (id_municipio, nombre, id_departamento) VALUES (0408, 'Pochuta', 04);
INSERT INTO municipio (id_municipio, nombre, id_departamento) VALUES (0409, 'Patzicía', 04);
INSERT INTO municipio (id_municipio, nombre, id_departamento) VALUES (0410, 'Santa Cruz Balanyá', 04);
INSERT INTO municipio (id_municipio, nombre, id_departamento) VALUES (0411, 'Acatenango', 04);
INSERT INTO municipio (id_municipio, nombre, id_departamento) VALUES (0412, 'Yepocapa', 04);
INSERT INTO municipio (id_municipio, nombre, id_departamento) VALUES (0413, 'San Andrés Itzapa', 04);
INSERT INTO municipio (id_municipio, nombre, id_departamento) VALUES (0414, 'Parramos', 04);
INSERT INTO municipio (id_municipio, nombre, id_departamento) VALUES (0415, 'Zaragoza', 04);
INSERT INTO municipio (id_municipio, nombre, id_departamento) VALUES (0416, 'El Tejar', 04);
INSERT INTO municipio (id_municipio, nombre, id_departamento) VALUES (0501, 'Escuintla', 05);
INSERT INTO municipio (id_municipio, nombre, id_departamento) VALUES (0502, 'Santa Lucía Cotzumalguapa', 05);
INSERT INTO municipio (id_municipio, nombre, id_departamento) VALUES (0503, 'La Democracia', 05);
INSERT INTO municipio (id_municipio, nombre, id_departamento) VALUES (0504, 'Siquinalá', 05);
INSERT INTO municipio (id_municipio, nombre, id_departamento) VALUES (0505, 'Masagua', 05);
INSERT INTO municipio (id_municipio, nombre, id_departamento) VALUES (0506, 'Tiquisate', 05);
INSERT INTO municipio (id_municipio, nombre, id_departamento) VALUES (0507, 'La Gomera', 05);
INSERT INTO municipio (id_municipio, nombre, id_departamento) VALUES (0508, 'Guanagazapa', 05);
INSERT INTO municipio (id_municipio, nombre, id_departamento) VALUES (0509, 'San José', 05);
INSERT INTO municipio (id_municipio, nombre, id_departamento) VALUES (0510, 'Iztapa', 05);
INSERT INTO municipio (id_municipio, nombre, id_departamento) VALUES (0511, 'Palín', 05);
INSERT INTO municipio (id_municipio, nombre, id_departamento) VALUES (0512, 'San Vicente Pacaya', 05);
INSERT INTO municipio (id_municipio, nombre, id_departamento) VALUES (0513, 'Nueva Concepción', 05);
INSERT INTO municipio (id_municipio, nombre, id_departamento) VALUES (0601, 'Cuilapa', 06);
INSERT INTO municipio (id_municipio, nombre, id_departamento) VALUES (0602, 'Barberena', 06);
INSERT INTO municipio (id_municipio, nombre, id_departamento) VALUES (0603, 'Santa Rosa de Lima', 06);
INSERT INTO municipio (id_municipio, nombre, id_departamento) VALUES (0604, 'Casillas', 06);
INSERT INTO municipio (id_municipio, nombre, id_departamento) VALUES (0605, 'San Rafael las Flores', 06);
INSERT INTO municipio (id_municipio, nombre, id_departamento) VALUES (0606, 'Oratorio', 06);
INSERT INTO municipio (id_municipio, nombre, id_departamento) VALUES (0607, 'San Juan Tecuaco', 06);
INSERT INTO municipio (id_municipio, nombre, id_departamento) VALUES (0608, 'Chiquimulilla', 06);
INSERT INTO municipio (id_municipio, nombre, id_departamento) VALUES (0609, 'Taxisco', 06);
INSERT INTO municipio (id_municipio, nombre, id_departamento) VALUES (0610, 'Santa María Ixhuatán', 06);
INSERT INTO municipio (id_municipio, nombre, id_departamento) VALUES (0611, 'Guazacapán', 06);
INSERT INTO municipio (id_municipio, nombre, id_departamento) VALUES (0612, 'Santa Cruz Naranjo', 06);
INSERT INTO municipio (id_municipio, nombre, id_departamento) VALUES (0613, 'Pueblo Nuevo Viñas', 06);
INSERT INTO municipio (id_municipio, nombre, id_departamento) VALUES (0614, 'Nueva Santa Rosa', 06);
INSERT INTO municipio (id_municipio, nombre, id_departamento) VALUES (0701, 'Sololá', 07);
INSERT INTO municipio (id_municipio, nombre, id_departamento) VALUES (0702, 'San José Chacayá', 07);
INSERT INTO municipio (id_municipio, nombre, id_departamento) VALUES (0703, 'Santa María Visitación', 07);
INSERT INTO municipio (id_municipio, nombre, id_departamento) VALUES (0704, 'Santa Lucía Utatlán', 07);
INSERT INTO municipio (id_municipio, nombre, id_departamento) VALUES (0705, 'Nahualá', 07);
INSERT INTO municipio (id_municipio, nombre, id_departamento) VALUES (0706, 'Santa Catarina Ixtahuacán', 07);
INSERT INTO municipio (id_municipio, nombre, id_departamento) VALUES (0707, 'Santa Clara la Laguna', 07);
INSERT INTO municipio (id_municipio, nombre, id_departamento) VALUES (0708, 'Concepción', 07);
INSERT INTO municipio (id_municipio, nombre, id_departamento) VALUES (0709, 'San Andrés Semetabaj', 07);
INSERT INTO municipio (id_municipio, nombre, id_departamento) VALUES (0710, 'Panajachel', 07);
INSERT INTO municipio (id_municipio, nombre, id_departamento) VALUES (0711, 'Santa Catarina Palopó', 07);
INSERT INTO municipio (id_municipio, nombre, id_departamento) VALUES (0712, 'San Antonio Palopó', 07);
INSERT INTO municipio (id_municipio, nombre, id_departamento) VALUES (0713, 'San Lucas Tolimán', 07);
INSERT INTO municipio (id_municipio, nombre, id_departamento) VALUES (0714, 'Santa Cruz la Laguna', 07);
INSERT INTO municipio (id_municipio, nombre, id_departamento) VALUES (0715, 'San Pablo la Laguna', 07);
INSERT INTO municipio (id_municipio, nombre, id_departamento) VALUES (0716, 'San Marcos la Laguna', 07);
INSERT INTO municipio (id_municipio, nombre, id_departamento) VALUES (0717, 'San Juan la Laguna', 07);
INSERT INTO municipio (id_municipio, nombre, id_departamento) VALUES (0718, 'San Pedro la Laguna', 07);
INSERT INTO municipio (id_municipio, nombre, id_departamento) VALUES (0719, 'Santiago Atitlán', 07);
INSERT INTO municipio (id_municipio, nombre, id_departamento) VALUES (0801, 'Totonicapán', 08);
INSERT INTO municipio (id_municipio, nombre, id_departamento) VALUES (0802, 'San Cristóbal Totonicapán', 08);
INSERT INTO municipio (id_municipio, nombre, id_departamento) VALUES (0803, 'San Francisco el Alto', 08);
INSERT INTO municipio (id_municipio, nombre, id_departamento) VALUES (0804, 'San Andrés Xecul', 08);
INSERT INTO municipio (id_municipio, nombre, id_departamento) VALUES (0805, 'Momostenango', 08);
INSERT INTO municipio (id_municipio, nombre, id_departamento) VALUES (0806, 'Santa María Chiquimula', 08);
INSERT INTO municipio (id_municipio, nombre, id_departamento) VALUES (0807, 'Santa Lucía la Reforma', 08);
INSERT INTO municipio (id_municipio, nombre, id_departamento) VALUES (0808, 'San Bartolo', 08);
INSERT INTO municipio (id_municipio, nombre, id_departamento) VALUES (0901, 'Quetzaltenango', 09);
INSERT INTO municipio (id_municipio, nombre, id_departamento) VALUES (0902, 'Salcajá', 09);
INSERT INTO municipio (id_municipio, nombre, id_departamento) VALUES (0903, 'Olintepeque', 09);
INSERT INTO municipio (id_municipio, nombre, id_departamento) VALUES (0904, 'San Carlos Sija', 09);
INSERT INTO municipio (id_municipio, nombre, id_departamento) VALUES (0905, 'Sibilia', 09);
INSERT INTO municipio (id_municipio, nombre, id_departamento) VALUES (0906, 'Cabricán', 09);
INSERT INTO municipio (id_municipio, nombre, id_departamento) VALUES (0907, 'Cajolá', 09);
INSERT INTO municipio (id_municipio, nombre, id_departamento) VALUES (0908, 'San Miguel Siguilá', 09);
INSERT INTO municipio (id_municipio, nombre, id_departamento) VALUES (0909, 'Ostuncalco', 09);
INSERT INTO municipio (id_municipio, nombre, id_departamento) VALUES (0910, 'San Mateo', 09);
INSERT INTO municipio (id_municipio, nombre, id_departamento) VALUES (0911, 'Concepción Chiquirichapa', 09);
INSERT INTO municipio (id_municipio, nombre, id_departamento) VALUES (0912, 'San Martín Sacatepéquez', 09);
INSERT INTO municipio (id_municipio, nombre, id_departamento) VALUES (0913, 'Almolonga', 09);
INSERT INTO municipio (id_municipio, nombre, id_departamento) VALUES (0914, 'Cantel', 09);
INSERT INTO municipio (id_municipio, nombre, id_departamento) VALUES (0915, 'Huitán', 09);
INSERT INTO municipio (id_municipio, nombre, id_departamento) VALUES (0916, 'Zunil', 09);
INSERT INTO municipio (id_municipio, nombre, id_departamento) VALUES (0917, 'Colomba', 09);
INSERT INTO municipio (id_municipio, nombre, id_departamento) VALUES (0918, 'San Francisco la Unión', 09);
INSERT INTO municipio (id_municipio, nombre, id_departamento) VALUES (0919, 'El Palmar', 09);
INSERT INTO municipio (id_municipio, nombre, id_departamento) VALUES (0920, 'Coatepeque', 09);
INSERT INTO municipio (id_municipio, nombre, id_departamento) VALUES (0921, 'Génova', 09);
INSERT INTO municipio (id_municipio, nombre, id_departamento) VALUES (0922, 'Flores Costa Cuca', 09);
INSERT INTO municipio (id_municipio, nombre, id_departamento) VALUES (0923, 'La Esperanza', 09);
INSERT INTO municipio (id_municipio, nombre, id_departamento) VALUES (0924, 'Palestina de los Altos', 09);
INSERT INTO municipio (id_municipio, nombre, id_departamento) VALUES (1001, 'Mazatenango', 10);
INSERT INTO municipio (id_municipio, nombre, id_departamento) VALUES (1002, 'Cuyotenango', 10);
INSERT INTO municipio (id_municipio, nombre, id_departamento) VALUES (1003, 'San Francisco Zapotitlán', 10);
INSERT INTO municipio (id_municipio, nombre, id_departamento) VALUES (1004, 'San Bernardino', 10);
INSERT INTO municipio (id_municipio, nombre, id_departamento) VALUES (1005, 'San José el Idolo', 10);
INSERT INTO municipio (id_municipio, nombre, id_departamento) VALUES (1006, 'Santo Domingo Suchitepéquez', 10);
INSERT INTO municipio (id_municipio, nombre, id_departamento) VALUES (1007, 'San Lorenzo', 10);
INSERT INTO municipio (id_municipio, nombre, id_departamento) VALUES (1008, 'Samayac', 10);
INSERT INTO municipio (id_municipio, nombre, id_departamento) VALUES (1009, 'San Pablo Jocopilas', 10);
INSERT INTO municipio (id_municipio, nombre, id_departamento) VALUES (1010, 'San Antonio Suchitepéquez', 10);
INSERT INTO municipio (id_municipio, nombre, id_departamento) VALUES (1011, 'San Miguel Panán', 10);
INSERT INTO municipio (id_municipio, nombre, id_departamento) VALUES (1012, 'San Gabriel', 10);
INSERT INTO municipio (id_municipio, nombre, id_departamento) VALUES (1013, 'Chicacao', 10);
INSERT INTO municipio (id_municipio, nombre, id_departamento) VALUES (1014, 'Patulul', 10);
INSERT INTO municipio (id_municipio, nombre, id_departamento) VALUES (1015, 'Santa Bárbara', 10);
INSERT INTO municipio (id_municipio, nombre, id_departamento) VALUES (1016, 'San Juan Bautista', 10);
INSERT INTO municipio (id_municipio, nombre, id_departamento) VALUES (1017, 'Santo Tomás la Unión', 10);
INSERT INTO municipio (id_municipio, nombre, id_departamento) VALUES (1018, 'Zunilito', 10);
INSERT INTO municipio (id_municipio, nombre, id_departamento) VALUES (1019, 'Pueblo Nuevo', 10);
INSERT INTO municipio (id_municipio, nombre, id_departamento) VALUES (1020, 'Río Bravo', 10);
INSERT INTO municipio (id_municipio, nombre, id_departamento) VALUES (1021, 'San José La Máquina', 10);
INSERT INTO municipio (id_municipio, nombre, id_departamento) VALUES (1101, 'Retalhuleu', 11);
INSERT INTO municipio (id_municipio, nombre, id_departamento) VALUES (1102, 'San Sebastián', 11);
INSERT INTO municipio (id_municipio, nombre, id_departamento) VALUES (1103, 'Santa Cruz Muluá', 11);
INSERT INTO municipio (id_municipio, nombre, id_departamento) VALUES (1104, 'San Martín Zapotitlán', 11);
INSERT INTO municipio (id_municipio, nombre, id_departamento) VALUES (1105, 'San Felipe', 11);
INSERT INTO municipio (id_municipio, nombre, id_departamento) VALUES (1106, 'San Andrés Villa Seca', 11);
INSERT INTO municipio (id_municipio, nombre, id_departamento) VALUES (1107, 'Champerico', 11);
INSERT INTO municipio (id_municipio, nombre, id_departamento) VALUES (1108, 'Nuevo San Carlos', 11);
INSERT INTO municipio (id_municipio, nombre, id_departamento) VALUES (1109, 'El Asintal', 11);
INSERT INTO municipio (id_municipio, nombre, id_departamento) VALUES (1201, 'San Marcos', 12);
INSERT INTO municipio (id_municipio, nombre, id_departamento) VALUES (1202, 'San Pedro Sacatepéquez', 12);
INSERT INTO municipio (id_municipio, nombre, id_departamento) VALUES (1203, 'San Antonio Sacatepéquez', 12);
INSERT INTO municipio (id_municipio, nombre, id_departamento) VALUES (1204, 'Comitancillo', 12);
INSERT INTO municipio (id_municipio, nombre, id_departamento) VALUES (1205, 'San Miguel Ixtahuacán', 12);
INSERT INTO municipio (id_municipio, nombre, id_departamento) VALUES (1206, 'Concepción Tutuapa', 12);
INSERT INTO municipio (id_municipio, nombre, id_departamento) VALUES (1207, 'Tacaná', 12);
INSERT INTO municipio (id_municipio, nombre, id_departamento) VALUES (1208, 'Sibinal', 12);
INSERT INTO municipio (id_municipio, nombre, id_departamento) VALUES (1209, 'Tajumulco', 12);
INSERT INTO municipio (id_municipio, nombre, id_departamento) VALUES (1210, 'Tejutla', 12);
INSERT INTO municipio (id_municipio, nombre, id_departamento) VALUES (1211, 'San Rafael Pié de la Cuesta', 12);
INSERT INTO municipio (id_municipio, nombre, id_departamento) VALUES (1212, 'Nuevo Progreso', 12);
INSERT INTO municipio (id_municipio, nombre, id_departamento) VALUES (1213, 'El Tumbador', 12);
INSERT INTO municipio (id_municipio, nombre, id_departamento) VALUES (1214, 'El Rodeo', 12);
INSERT INTO municipio (id_municipio, nombre, id_departamento) VALUES (1215, 'Malacatán', 12);
INSERT INTO municipio (id_municipio, nombre, id_departamento) VALUES (1216, 'Catarina', 12);
INSERT INTO municipio (id_municipio, nombre, id_departamento) VALUES (1217, 'Ayutla', 12);
INSERT INTO municipio (id_municipio, nombre, id_departamento) VALUES (1218, 'Ocós', 12);
INSERT INTO municipio (id_municipio, nombre, id_departamento) VALUES (1219, 'San Pablo', 12);
INSERT INTO municipio (id_municipio, nombre, id_departamento) VALUES (1220, 'El Quetzal', 12);
INSERT INTO municipio (id_municipio, nombre, id_departamento) VALUES (1221, 'La Reforma', 12);
INSERT INTO municipio (id_municipio, nombre, id_departamento) VALUES (1222, 'Pajapita', 12);
INSERT INTO municipio (id_municipio, nombre, id_departamento) VALUES (1223, 'Ixchiguán', 12);
INSERT INTO municipio (id_municipio, nombre, id_departamento) VALUES (1224, 'San José Ojetenán', 12);
INSERT INTO municipio (id_municipio, nombre, id_departamento) VALUES (1225, 'San Cristóbal Cucho', 12);
INSERT INTO municipio (id_municipio, nombre, id_departamento) VALUES (1226, 'Sipacapa', 12);
INSERT INTO municipio (id_municipio, nombre, id_departamento) VALUES (1227, 'Esquipulas Palo Gordo', 12);
INSERT INTO municipio (id_municipio, nombre, id_departamento) VALUES (1228, 'Río Blanco', 12);
INSERT INTO municipio (id_municipio, nombre, id_departamento) VALUES (1229, 'San Lorenzo', 12);
INSERT INTO municipio (id_municipio, nombre, id_departamento) VALUES (1230, 'La Blanca', 12);
INSERT INTO municipio (id_municipio, nombre, id_departamento) VALUES (1301, 'Huehuetenango', 13);
INSERT INTO municipio (id_municipio, nombre, id_departamento) VALUES (1302, 'Chiantla', 13);
INSERT INTO municipio (id_municipio, nombre, id_departamento) VALUES (1303, 'Malacatancito', 13);
INSERT INTO municipio (id_municipio, nombre, id_departamento) VALUES (1304, 'Cuilco', 13);
INSERT INTO municipio (id_municipio, nombre, id_departamento) VALUES (1305, 'Nentón', 13);
INSERT INTO municipio (id_municipio, nombre, id_departamento) VALUES (1306, 'San Pedro Necta', 13);
INSERT INTO municipio (id_municipio, nombre, id_departamento) VALUES (1307, 'Jacaltenango', 13);
INSERT INTO municipio (id_municipio, nombre, id_departamento) VALUES (1308, 'Soloma', 13);
INSERT INTO municipio (id_municipio, nombre, id_departamento) VALUES (1309, 'Ixtahuacán', 13);
INSERT INTO municipio (id_municipio, nombre, id_departamento) VALUES (1310, 'Santa Bárbara', 13);
INSERT INTO municipio (id_municipio, nombre, id_departamento) VALUES (1311, 'La Libertad', 13);
INSERT INTO municipio (id_municipio, nombre, id_departamento) VALUES (1312, 'La Democracia', 13);
INSERT INTO municipio (id_municipio, nombre, id_departamento) VALUES (1313, 'San Miguel Acatán', 13);
INSERT INTO municipio (id_municipio, nombre, id_departamento) VALUES (1314, 'San Rafael la Independencia', 13);
INSERT INTO municipio (id_municipio, nombre, id_departamento) VALUES (1315, 'Todos Santos Cuchumatán', 13);
INSERT INTO municipio (id_municipio, nombre, id_departamento) VALUES (1316, 'San Juan Atitán', 13);
INSERT INTO municipio (id_municipio, nombre, id_departamento) VALUES (1317, 'Santa Eulalia', 13);
INSERT INTO municipio (id_municipio, nombre, id_departamento) VALUES (1318, 'San Mateo Ixtatán', 13);
INSERT INTO municipio (id_municipio, nombre, id_departamento) VALUES (1319, 'Colotenango', 13);
INSERT INTO municipio (id_municipio, nombre, id_departamento) VALUES (1320, 'San Sebastián Huehuetenango', 13);
INSERT INTO municipio (id_municipio, nombre, id_departamento) VALUES (1321, 'Tectitán', 13);
INSERT INTO municipio (id_municipio, nombre, id_departamento) VALUES (1322, 'Concepción Huista', 13);
INSERT INTO municipio (id_municipio, nombre, id_departamento) VALUES (1323, 'San Juan Ixcoy', 13);
INSERT INTO municipio (id_municipio, nombre, id_departamento) VALUES (1324, 'San Antonio Huista', 13);
INSERT INTO municipio (id_municipio, nombre, id_departamento) VALUES (1325, 'San Sebastián Coatán', 13);
INSERT INTO municipio (id_municipio, nombre, id_departamento) VALUES (1326, 'Barillas', 13);
INSERT INTO municipio (id_municipio, nombre, id_departamento) VALUES (1327, 'Aguacatán', 13);
INSERT INTO municipio (id_municipio, nombre, id_departamento) VALUES (1328, 'San Rafael Petzal', 13);
INSERT INTO municipio (id_municipio, nombre, id_departamento) VALUES (1329, 'San Gaspar Ixchil', 13);
INSERT INTO municipio (id_municipio, nombre, id_departamento) VALUES (1330, 'Santiago Chimaltenango', 13);
INSERT INTO municipio (id_municipio, nombre, id_departamento) VALUES (1331, 'Santa Ana Huista', 13);
INSERT INTO municipio (id_municipio, nombre, id_departamento) VALUES (1332, 'Unión Cantinil', 13);
INSERT INTO municipio (id_municipio, nombre, id_departamento) VALUES (1401, 'Santa Cruz del Quiché', 14);
INSERT INTO municipio (id_municipio, nombre, id_departamento) VALUES (1402, 'Chiché', 14);
INSERT INTO municipio (id_municipio, nombre, id_departamento) VALUES (1403, 'Chinique', 14);
INSERT INTO municipio (id_municipio, nombre, id_departamento) VALUES (1404, 'Zacualpa', 14);
INSERT INTO municipio (id_municipio, nombre, id_departamento) VALUES (1405, 'Chajul', 14);
INSERT INTO municipio (id_municipio, nombre, id_departamento) VALUES (1406, 'Chichicastenango', 14);
INSERT INTO municipio (id_municipio, nombre, id_departamento) VALUES (1407, 'Patzité', 14);
INSERT INTO municipio (id_municipio, nombre, id_departamento) VALUES (1408, 'San Antonio Ilotenango', 14);
INSERT INTO municipio (id_municipio, nombre, id_departamento) VALUES (1409, 'San Pedro Jocopilas', 14);
INSERT INTO municipio (id_municipio, nombre, id_departamento) VALUES (1410, 'Cunén', 14);
INSERT INTO municipio (id_municipio, nombre, id_departamento) VALUES (1411, 'San Juan Cotzal', 14);
INSERT INTO municipio (id_municipio, nombre, id_departamento) VALUES (1412, 'Joyabaj', 14);
INSERT INTO municipio (id_municipio, nombre, id_departamento) VALUES (1413, 'Nebaj', 14);
INSERT INTO municipio (id_municipio, nombre, id_departamento) VALUES (1414, 'San Andrés Sajcabajá', 14);
INSERT INTO municipio (id_municipio, nombre, id_departamento) VALUES (1415, 'Uspantán', 14);
INSERT INTO municipio (id_municipio, nombre, id_departamento) VALUES (1416, 'Sacapulas', 14);
INSERT INTO municipio (id_municipio, nombre, id_departamento) VALUES (1417, 'San Bartolomé Jocotenango', 14);
INSERT INTO municipio (id_municipio, nombre, id_departamento) VALUES (1418, 'Canillá', 14);
INSERT INTO municipio (id_municipio, nombre, id_departamento) VALUES (1419, 'Chicamán', 14);
INSERT INTO municipio (id_municipio, nombre, id_departamento) VALUES (1420, 'Ixcán', 14);
INSERT INTO municipio (id_municipio, nombre, id_departamento) VALUES (1421, 'Pachalum', 14);
INSERT INTO municipio (id_municipio, nombre, id_departamento) VALUES (1501, 'Salamá', 15);
INSERT INTO municipio (id_municipio, nombre, id_departamento) VALUES (1502, 'San Miguel Chicaj', 15);
INSERT INTO municipio (id_municipio, nombre, id_departamento) VALUES (1503, 'Rabinal', 15);
INSERT INTO municipio (id_municipio, nombre, id_departamento) VALUES (1504, 'Cubulco', 15);
INSERT INTO municipio (id_municipio, nombre, id_departamento) VALUES (1505, 'Granados', 15);
INSERT INTO municipio (id_municipio, nombre, id_departamento) VALUES (1506, 'El Chol', 15);
INSERT INTO municipio (id_municipio, nombre, id_departamento) VALUES (1507, 'San Jerónimo', 15);
INSERT INTO municipio (id_municipio, nombre, id_departamento) VALUES (1508, 'Purulhá', 15);
INSERT INTO municipio (id_municipio, nombre, id_departamento) VALUES (1601, 'Cobán', 16);
INSERT INTO municipio (id_municipio, nombre, id_departamento) VALUES (1602, 'Santa Cruz Verapaz', 16);
INSERT INTO municipio (id_municipio, nombre, id_departamento) VALUES (1603, 'San Cristóbal Verapaz', 16);
INSERT INTO municipio (id_municipio, nombre, id_departamento) VALUES (1604, 'Tactic', 16);
INSERT INTO municipio (id_municipio, nombre, id_departamento) VALUES (1605, 'Tamahú', 16);
INSERT INTO municipio (id_municipio, nombre, id_departamento) VALUES (1606, 'Tucurú', 16);
INSERT INTO municipio (id_municipio, nombre, id_departamento) VALUES (1607, 'Panzós', 16);
INSERT INTO municipio (id_municipio, nombre, id_departamento) VALUES (1608, 'Senahú', 16);
INSERT INTO municipio (id_municipio, nombre, id_departamento) VALUES (1609, 'San Pedro Carchá', 16);
INSERT INTO municipio (id_municipio, nombre, id_departamento) VALUES (1610, 'San Juan Chamelco', 16);
INSERT INTO municipio (id_municipio, nombre, id_departamento) VALUES (1611, 'Lanquín', 16);
INSERT INTO municipio (id_municipio, nombre, id_departamento) VALUES (1612, 'Cahabón', 16);
INSERT INTO municipio (id_municipio, nombre, id_departamento) VALUES (1613, 'Chisec', 16);
INSERT INTO municipio (id_municipio, nombre, id_departamento) VALUES (1614, 'Chahal', 16);
INSERT INTO municipio (id_municipio, nombre, id_departamento) VALUES (1615, 'Fray Bartolomé de las Casas', 16);
INSERT INTO municipio (id_municipio, nombre, id_departamento) VALUES (1616, 'Santa Catalina la Tinta', 16);
INSERT INTO municipio (id_municipio, nombre, id_departamento) VALUES (1617, 'Raxruhá', 16);
INSERT INTO municipio (id_municipio, nombre, id_departamento) VALUES (1701, 'Flores', 17);
INSERT INTO municipio (id_municipio, nombre, id_departamento) VALUES (1702, 'San José', 17);
INSERT INTO municipio (id_municipio, nombre, id_departamento) VALUES (1703, 'San Benito', 17);
INSERT INTO municipio (id_municipio, nombre, id_departamento) VALUES (1704, 'San Andrés', 17);
INSERT INTO municipio (id_municipio, nombre, id_departamento) VALUES (1705, 'La Libertad', 17);
INSERT INTO municipio (id_municipio, nombre, id_departamento) VALUES (1706, 'San Francisco', 17);
INSERT INTO municipio (id_municipio, nombre, id_departamento) VALUES (1707, 'Santa Ana', 17);
INSERT INTO municipio (id_municipio, nombre, id_departamento) VALUES (1708, 'Dolores', 17);
INSERT INTO municipio (id_municipio, nombre, id_departamento) VALUES (1709, 'San Luis', 17);
INSERT INTO municipio (id_municipio, nombre, id_departamento) VALUES (1710, 'Sayaxché', 17);
INSERT INTO municipio (id_municipio, nombre, id_departamento) VALUES (1711, 'Melchor de Mencos', 17);
INSERT INTO municipio (id_municipio, nombre, id_departamento) VALUES (1712, 'Poptún', 17);
INSERT INTO municipio (id_municipio, nombre, id_departamento) VALUES (1713, 'Las Cruces', 17);
INSERT INTO municipio (id_municipio, nombre, id_departamento) VALUES (1714, 'El Chal', 17);
INSERT INTO municipio (id_municipio, nombre, id_departamento) VALUES (1801, 'Puerto Barrios', 18);
INSERT INTO municipio (id_municipio, nombre, id_departamento) VALUES (1802, 'Livingston', 18);
INSERT INTO municipio (id_municipio, nombre, id_departamento) VALUES (1803, 'El Estor', 18);
INSERT INTO municipio (id_municipio, nombre, id_departamento) VALUES (1804, 'Morales', 18);
INSERT INTO municipio (id_municipio, nombre, id_departamento) VALUES (1805, 'Los Amates', 18);
INSERT INTO municipio (id_municipio, nombre, id_departamento) VALUES (1901, 'Zacapa', 19);
INSERT INTO municipio (id_municipio, nombre, id_departamento) VALUES (1902, 'Estanzuela', 19);
INSERT INTO municipio (id_municipio, nombre, id_departamento) VALUES (1903, 'Río Hondo', 19);
INSERT INTO municipio (id_municipio, nombre, id_departamento) VALUES (1904, 'Gualán', 19);
INSERT INTO municipio (id_municipio, nombre, id_departamento) VALUES (1905, 'Teculután', 19);
INSERT INTO municipio (id_municipio, nombre, id_departamento) VALUES (1906, 'Usumatlán', 19);
INSERT INTO municipio (id_municipio, nombre, id_departamento) VALUES (1907, 'Cabañas', 19);
INSERT INTO municipio (id_municipio, nombre, id_departamento) VALUES (1908, 'San Diego', 19);
INSERT INTO municipio (id_municipio, nombre, id_departamento) VALUES (1909, 'La Unión', 19);
INSERT INTO municipio (id_municipio, nombre, id_departamento) VALUES (1910, 'Huité', 19);
INSERT INTO municipio (id_municipio, nombre, id_departamento) VALUES (1911, 'San Jorge', 19);
INSERT INTO municipio (id_municipio, nombre, id_departamento) VALUES (2001, 'Chiquimula', 20);
INSERT INTO municipio (id_municipio, nombre, id_departamento) VALUES (2002, 'San José La Arada', 20);
INSERT INTO municipio (id_municipio, nombre, id_departamento) VALUES (2003, 'San Juan Ermita', 20);
INSERT INTO municipio (id_municipio, nombre, id_departamento) VALUES (2004, 'Jocotán', 20);
INSERT INTO municipio (id_municipio, nombre, id_departamento) VALUES (2005, 'Camotán', 20);
INSERT INTO municipio (id_municipio, nombre, id_departamento) VALUES (2006, 'Olopa', 20);
INSERT INTO municipio (id_municipio, nombre, id_departamento) VALUES (2007, 'Esquipulas', 20);
INSERT INTO municipio (id_municipio, nombre, id_departamento) VALUES (2008, 'Concepción Las Minas', 20);
INSERT INTO municipio (id_municipio, nombre, id_departamento) VALUES (2009, 'Quetzaltepeque', 20);
INSERT INTO municipio (id_municipio, nombre, id_departamento) VALUES (2010, 'San Jacinto', 20);
INSERT INTO municipio (id_municipio, nombre, id_departamento) VALUES (2011, 'Ipala', 20);
INSERT INTO municipio (id_municipio, nombre, id_departamento) VALUES (2101, 'Jalapa', 21);
INSERT INTO municipio (id_municipio, nombre, id_departamento) VALUES (2102, 'San Pedro Pinula', 21);
INSERT INTO municipio (id_municipio, nombre, id_departamento) VALUES (2103, 'San Luis Jilotepeque', 21);
INSERT INTO municipio (id_municipio, nombre, id_departamento) VALUES (2104, 'San Manuel Chaparrón', 21);
INSERT INTO municipio (id_municipio, nombre, id_departamento) VALUES (2105, 'San Carlos Alzatate', 21);
INSERT INTO municipio (id_municipio, nombre, id_departamento) VALUES (2106, 'Monjas', 21);
INSERT INTO municipio (id_municipio, nombre, id_departamento) VALUES (2107, 'Mataquescuintla', 21);
INSERT INTO municipio (id_municipio, nombre, id_departamento) VALUES (2201, 'Jutiapa', 22);
INSERT INTO municipio (id_municipio, nombre, id_departamento) VALUES (2202, 'El Progreso', 22);
INSERT INTO municipio (id_municipio, nombre, id_departamento) VALUES (2203, 'Santa Catarina Mita', 22);
INSERT INTO municipio (id_municipio, nombre, id_departamento) VALUES (2204, 'Agua Blanca', 22);
INSERT INTO municipio (id_municipio, nombre, id_departamento) VALUES (2205, 'Asunción Mita', 22);
INSERT INTO municipio (id_municipio, nombre, id_departamento) VALUES (2206, 'Yupiltepeque', 22);
INSERT INTO municipio (id_municipio, nombre, id_departamento) VALUES (2207, 'Atescatempa', 22);
INSERT INTO municipio (id_municipio, nombre, id_departamento) VALUES (2208, 'Jerez', 22);
INSERT INTO municipio (id_municipio, nombre, id_departamento) VALUES (2209, 'El Adelanto', 22);
INSERT INTO municipio (id_municipio, nombre, id_departamento) VALUES (2210, 'Zapotitlán', 22);
INSERT INTO municipio (id_municipio, nombre, id_departamento) VALUES (2211, 'Comapa', 22);
INSERT INTO municipio (id_municipio, nombre, id_departamento) VALUES (2212, 'Jalpatagua', 22);
INSERT INTO municipio (id_municipio, nombre, id_departamento) VALUES (2213, 'Conguaco', 22);
INSERT INTO municipio (id_municipio, nombre, id_departamento) VALUES (2214, 'Moyuta', 22);
INSERT INTO municipio (id_municipio, nombre, id_departamento) VALUES (2215, 'Pasaco', 22);
INSERT INTO municipio (id_municipio, nombre, id_departamento) VALUES (2216, 'San José Acatempa', 22);
INSERT INTO municipio (id_municipio, nombre, id_departamento) VALUES (2217, 'Quesada', 22);
